import {useEffect,useMemo,useState} from "react"; import {Search,Settings,MoreHorizontal,ChevronRight,Plus,Command,Archive,Undo2} from "lucide-react"; import {db,type Note} from "./db/db"; import {ensureSeed} from "./db/seed"; import {Editor} from "./editor/Editor"; import {nanoid} from "nanoid"; import {useLiveQuery} from "dexie-react-hooks";
export function App(){const notes=useLiveQuery(()=>db.notes.toArray(),[])||[]; const [selected,setSelected]=useState<string|null>(null); const [query,setQuery]=useState(""); const [palette,setPalette]=useState(false); const [theme,setTheme]=useState(localStorage.getItem("nesti-theme")||"system"); useEffect(()=>{ensureSeed()},[]); useEffect(()=>{if(!selected&&notes.length)setSelected(notes.find(n=>!n.isArchived)?.id||null)},[notes,selected]); useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem("nesti-theme",theme)},[theme]); useEffect(()=>{const h=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setPalette(true)} if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="n"){e.preventDefault();createNote(selected)} if(e.key==="Escape")setPalette(false)};window.addEventListener("keydown",h);return()=>window.removeEventListener("keydown",h)},[selected]);
const current=notes.find(n=>n.id===selected)||null; const results=useMemo(()=>query.trim()?notes.filter(n=>(n.title+" "+n.content+" "+n.tags.join(" ")).toLowerCase().includes(query.toLowerCase())&&!n.isArchived):[],[notes,query]);
async function createNote(parentId:string|null=null){const now=Date.now();const sibling=notes.filter(n=>n.parentId===parentId&&!n.isArchived);const n:Note={id:nanoid(),parentId,title:"Untitled",content:"<p></p>",createdAt:now,updatedAt:now,sortOrder:sibling.length,isFavorite:false,isArchived:false,isPinned:false,tags:[]};await db.notes.add(n);setSelected(n.id)}
async function updateContent(html:string){if(!current)return;const now=Date.now(); if(current.content!==html){await db.revisions.add({id:nanoid(),noteId:current.id,content:current.content,title:current.title,createdAt:now}); await db.notes.update(current.id,{content:html,updatedAt:now})}}
async function rename(id:string,title:string){await db.notes.update(id,{title:title||"Untitled",updatedAt:Date.now()})}
async function archive(id:string){await db.notes.update(id,{isArchived:true,updatedAt:Date.now()}); if(selected===id)setSelected(notes.find(n=>n.id!==id&&!n.isArchived)?.id||null)}
async function reparent(targetId:string,childId:string){if(targetId===childId)return; await db.notes.update(childId,{parentId:targetId,sortOrder:(notes.filter(n=>n.parentId===targetId).length),updatedAt:Date.now()});}
return <div className="app"><SidebarWrap notes={notes} selected={selected} onSelect={setSelected} onNew={()=>createNote(null)} onNewChild={id=>{const dragged=(document.activeElement as HTMLElement)?.dataset?.note; if(dragged)reparent(id,dragged);else createNote(id)}} onArchive={archive} onToggleFavorite={id=>{const n=notes.find(x=>x.id===id);if(n)db.notes.update(id,{isFavorite:!n.isFavorite})}}/><main className="main"><header className="topbar"><div className="searchbox"><Search size={17}/><input placeholder="Search notes…" value={query} onChange={e=>setQuery(e.target.value)} onFocus={()=>{}}/><kbd>Ctrl K</kbd></div><button className="icon-btn" onClick={()=>setPalette(true)} title="Command palette"><Command size={17}/></button><button className="icon-btn" onClick={()=>setTheme(theme==="dark"?"light":"dark")} title="Toggle theme"><Settings size={17}/></button></header>{query&&<div className="search-results">{results.map(n=><button key={n.id} onClick={()=>{setSelected(n.id);setQuery("")}}><b>{n.title}</b><span>{strip(n.content).slice(0,100)}</span></button>)}{!results.length&&<div className="empty">No matching notes</div>}</div>}{current?<EditorPane note={current} onRename={rename} onChange={updateContent} onNewChild={()=>createNote(current.id)}/>:<div className="empty-state"><h1>Welcome to Nesti</h1><p>Simple notes. Powerful structure.</p><button onClick={()=>createNote(null)}>Create your first note</button></div>}</main>{palette&&<Palette notes={notes} onClose={()=>setPalette(false)} onCreate={()=>{setPalette(false);createNote(null)}} onSearch={()=>{setPalette(false);document.querySelector<HTMLInputElement>(".searchbox input")?.focus()}} onTheme={()=>{setPalette(false);setTheme(theme==="dark"?"light":"dark")}}/>}</div>}
function SidebarWrap(p:any){return <Sidebar {...p}/>}; import {Sidebar} from "./components/Sidebar";
function EditorPane({note,onRename,onChange,onNewChild}:{note:Note;onRename:(id:string,t:string)=>void;onChange:(h:string)=>void;onNewChild:()=>void}){const [title,setTitle]=useState(note.title);useEffect(()=>setTitle(note.title),[note.id,note.title]);return <section className="editor-pane"><div className="crumbs">{note.parentId&&<><span>Parent</span><ChevronRight size={13}/></>}<span>{note.title||"Untitled"}</span></div><input className="title-input" value={title} onChange={e=>setTitle(e.target.value)} onBlur={()=>onRename(note.id,title)} onKeyDown={e=>{if(e.key==="Enter")e.currentTarget.blur()}}/><Editor content={note.content} onChange={onChange}/><div className="subnotes"><div className="subhead"><b>Subnotes</b><button onClick={onNewChild}><Plus size={14}/> New subnote</button></div><p className="muted">Create nested notes from the sidebar or this section.</p></div><div className="saved">Saved locally · revisions enabled</div></section>}
function Palette({onClose,onCreate,onSearch,onTheme}:{notes:Note[];onClose:()=>void;onCreate:()=>void;onSearch:()=>void;onTheme:()=>void}){return <div className="overlay" onMouseDown={onClose}><div className="palette" onMouseDown={e=>e.stopPropagation()}><div className="palette-title">What do you want to do?</div><button onClick={onCreate}><Plus/> Create note <kbd>Ctrl N</kbd></button><button onClick={onSearch}><Search/> Search notes <kbd>Ctrl K</kbd></button><button onClick={onTheme}><Settings/> Toggle theme</button><button onClick={onClose}><Undo2/> Close <kbd>Esc</kbd></button></div></div>}
function strip(html:string){return html.replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim()};